name: Deploy Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Optional: If you have a build step, add here
    # - name: Build site
    #   run: |
    #     your build commands (e.g. npm install && npm run build)

    - name: Deploy to public repo
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Set this to your built site folder
        destination_repo: EliasGrove/fbmpub  # Replace "yourusername" with your GitHub username and your public repo name
        publish_branch: main  # Branch to publish to on the public repo
